import Link from 'next/link';
import { prisma } from '@allinall/database';
export const dynamic='force-dynamic';
function Stat({label,value,note}:{label:string;value:string|number;note:string}){return <article className="card stat"><small>{label}</small><strong>{value}</strong><small>{note}</small></article>}
export default async function Overview(){
 const now=new Date(); const startMonth=new Date(now.getFullYear(),now.getMonth(),1); const overdue=new Date();
 const [customers,leads,orders,projects,templates,pendingPayments,revenue,activities,audit]=await Promise.all([
  prisma.matrixCustomer.count({where:{deletedAt:null,status:'active'}}),prisma.matrixLead.count({where:{deletedAt:null,status:{in:['new','needs_review','qualified']}}}),prisma.matrixOrder.count({where:{deletedAt:null,status:{notIn:['completed','cancelled','archived']}}}),prisma.matrixProject.count({where:{deletedAt:null,status:{in:['planning','in_progress','waiting_client','testing']}}}),prisma.matrixTemplate.count({where:{deletedAt:null,status:'published'}}),prisma.matrixPayment.count({where:{deletedAt:null,status:'pending'}}),prisma.matrixFinancialTransaction.aggregate({where:{deletedAt:null,status:'posted',type:'income',occurredAt:{gte:startMonth}},_sum:{amount:true}}),prisma.matrixActivity.findMany({orderBy:{createdAt:'desc'},take:8,include:{actor:{select:{name:true}}}}),prisma.matrixAuditLog.findMany({orderBy:{createdAt:'desc'},take:8,include:{actor:{select:{name:true}}}})
 ]);
 return <div><header className="pageHeader"><div><span className="eyebrow">Executive overview</span><h1>لوحة القيادة المركزية</h1><p className="muted">قراءة مباشرة للعملاء والطلبات والمشاريع والقوالب والحركة المالية.</p></div><div className="toolbar"><Link className="btn primary" href="/manage/leads">إضافة طلب جديد</Link><Link className="btn" href="/manage/customers">إدارة العملاء</Link></div></header><section className="gridStats"><Stat label="العملاء النشطون" value={customers} note="حسابات غير مؤرشفة"/><Stat label="طلبات تحتاج إجراء" value={leads} note="جديدة أو مؤهلة"/><Stat label="المشاريع المفتوحة" value={projects} note="حتى مرحلة الاختبار"/><Stat label="إيراد الشهر" value={`${Number(revenue._sum.amount||0).toLocaleString('ar-EG')} ج.م`} note="المعاملات المرحلة كإيراد"/></section><section className="gridStats"><Stat label="طلبات قيد العمل" value={orders} note="غير مكتملة"/><Stat label="قوالب منشورة" value={templates} note="جاهزة للعرض والبيع"/><Stat label="مدفوعات منتظرة" value={pendingPayments} note="تحتاج تحصيل أو مراجعة"/><Stat label="حالة النظام" value="Operational" note="قاعدة البيانات متصلة"/></section><div className="split"><section className="panel"><div className="panelHead"><h2>آخر الأنشطة</h2><Link className="btn" href="/audit">فتح السجل</Link></div><div className="activity">{activities.length?activities.map(a=><div className="activityRow" key={a.id}><span className="activityDot"/><div><strong style={{fontSize:12}}>{a.title}</strong><div className="muted" style={{fontSize:10,marginTop:5}}>{a.actor?.name||'النظام'} • {new Date(a.createdAt).toLocaleString('ar-EG')}</div></div></div>):<div className="empty">لا توجد أنشطة بعد.</div>}</div></section><section className="panel"><div className="panelHead"><h2>العمليات الحساسة الأخيرة</h2></div><div className="activity">{audit.map(a=><div className="activityRow" key={a.id}><span className="activityDot" style={{background:a.result==='success'?'var(--success)':'var(--danger)'}}/><div><strong style={{fontSize:12}}>{a.action}</strong><div className="muted" style={{fontSize:10,marginTop:5}}>{a.entityType} • {a.actor?.name||'النظام'} • {new Date(a.createdAt).toLocaleString('ar-EG')}</div></div></div>)}</div></section></div></div>
}
