import { NextResponse } from 'next/server';
import { getDashboardSession } from '@/lib/auth';
import { canAccessResource } from '@/lib/permissions';
import { getDelegate, sanitizePayload } from '@/lib/resource-server';
import { recordAudit } from '@/lib/audit';

export async function PATCH(request:Request,{params}:{params:Promise<{resource:string;id:string}>}){const {resource,id}=await params;const session=await getDashboardSession();if(!session||!canAccessResource(session.user.role,resource,'update'))return NextResponse.json({error:'غير مصرح'},{status:403});const target=getDelegate(resource);if(!target)return NextResponse.json({error:'غير موجود'},{status:404});try{const before=await target.delegate.findUnique({where:{id}});if(!before)return NextResponse.json({error:'السجل غير موجود'},{status:404});const body=await request.json();const data=body.__action==='restore'?{deletedAt:null}:sanitizePayload(resource,body,true);const updated=await target.delegate.update({where:{id},data});await recordAudit({actorId:session.user.id,action:body.__action==='restore'?`${resource}.restore`:`${resource}.update`,entityType:target.definition.model,entityId:id,beforeData:before,afterData:updated,requestHeaders:request.headers});return NextResponse.json({item:updated});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'تعذر التعديل'},{status:400});}}

export async function DELETE(request:Request,{params}:{params:Promise<{resource:string;id:string}>}){const {resource,id}=await params;const session=await getDashboardSession();if(!session)return NextResponse.json({error:'غير مصرح'},{status:403});const url=new URL(request.url);const hard=url.searchParams.get('hard')==='1';const action=hard?'hardDelete':'delete';if(!canAccessResource(session.user.role,resource,action))return NextResponse.json({error:'غير مصرح بهذه العملية'},{status:403});const target=getDelegate(resource);if(!target)return NextResponse.json({error:'غير موجود'},{status:404});try{const before=await target.delegate.findUnique({where:{id}});if(!before)return NextResponse.json({error:'السجل غير موجود'},{status:404});if(hard)await target.delegate.delete({where:{id}});else if(target.definition.softDelete)await target.delegate.update({where:{id},data:{deletedAt:new Date()}});else return NextResponse.json({error:'هذا المورد لا يدعم الحذف الناعم'},{status:400});await recordAudit({actorId:session.user.id,action:hard?`${resource}.hard_delete`:`${resource}.soft_delete`,entityType:target.definition.model,entityId:id,beforeData:before,requestHeaders:request.headers});return NextResponse.json({ok:true});}catch(error){return NextResponse.json({error:'تعذر الحذف. قد توجد سجلات مرتبطة يجب التعامل معها أولًا.'},{status:409});}}
