import { NextResponse } from 'next/server';
import { getDashboardSession } from '@/lib/auth';
import { canAccessResource } from '@/lib/permissions';
import { buildSearchWhere, getDelegate, sanitizePayload } from '@/lib/resource-server';
import { recordAudit } from '@/lib/audit';

export async function GET(request:Request,{params}:{params:Promise<{resource:string}>}){const {resource}=await params;const session=await getDashboardSession();if(!session||!canAccessResource(session.user.role,resource,'read'))return NextResponse.json({error:'غير مصرح'}, {status:403});const target=getDelegate(resource);if(!target)return NextResponse.json({error:'المورد غير موجود'},{status:404});const url=new URL(request.url);const page=Math.max(1,Number(url.searchParams.get('page')||1));const limit=Math.min(100,Math.max(10,Number(url.searchParams.get('limit')||25)));const search=(url.searchParams.get('search')||'').trim();const includeDeleted=url.searchParams.get('deleted')==='1';const where=buildSearchWhere(resource,search,includeDeleted);const [items,total]=await Promise.all([target.delegate.findMany({where,orderBy:{updatedAt:'desc'},skip:(page-1)*limit,take:limit}),target.delegate.count({where})]);return NextResponse.json({items,total,page,limit,definition:target.definition});}

export async function POST(request:Request,{params}:{params:Promise<{resource:string}>}){const {resource}=await params;const session=await getDashboardSession();if(!session||!canAccessResource(session.user.role,resource,'create'))return NextResponse.json({error:'غير مصرح'},{status:403});const target=getDelegate(resource);if(!target)return NextResponse.json({error:'المورد غير موجود'},{status:404});try{const body=await request.json();const data=sanitizePayload(resource,body,false);const created=await target.delegate.create({data});await recordAudit({actorId:session.user.id,action:`${resource}.create`,entityType:target.definition.model,entityId:created.id,afterData:created,requestHeaders:request.headers});return NextResponse.json({item:created},{status:201});}catch(error){const message=error instanceof Error?error.message:'تعذر الحفظ';await recordAudit({actorId:session.user.id,action:`${resource}.create`,entityType:target.definition.model,result:'failure',failureReason:message,requestHeaders:request.headers});return NextResponse.json({error:message},{status:400});}}
