'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { FieldDefinition, ResourceDefinition } from '@/lib/resource-definitions';

type RecordData=Record<string,any>;
function formatValue(value:any,key:string){if(value===null||value===undefined||value==='')return '—';if(key.toLowerCase().includes('date')||key.endsWith('At')){const d=new Date(value);if(!Number.isNaN(d.getTime()))return d.toLocaleString('ar-EG');}if(typeof value==='boolean')return value?'نعم':'لا';if(typeof value==='object')return JSON.stringify(value);return String(value);}
export function DataManager({resource,definition}:{resource:string;definition:ResourceDefinition}){
 const[items,setItems]=useState<RecordData[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[search,setSearch]=useState(''),[deleted,setDeleted]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState<RecordData|null>(null),[open,setOpen]=useState(false),[options,setOptions]=useState<Record<string,{value:string;label:string}[]>>({});
 const pages=Math.max(1,Math.ceil(total/25));
 async function load(){setLoading(true);setError('');const r=await fetch(`/api/admin/${resource}?page=${page}&limit=25&search=${encodeURIComponent(search)}&deleted=${deleted?1:0}`,{cache:'no-store'});const d=await r.json();if(!r.ok){setError(d.error||'تعذر تحميل البيانات');setLoading(false);return;}setItems(d.items);setTotal(d.total);setLoading(false);}
 useEffect(()=>{void load()},[page,deleted]);
 useEffect(()=>{const relations=definition.fields.filter(f=>f.type==='relation'&&f.relationResource);Promise.all(relations.map(async f=>{const r=await fetch(`/api/admin/options/${f.relationResource}`);const d=await r.json();return [f.key,d.items||[]] as const})).then(rows=>setOptions(Object.fromEntries(rows)))},[resource]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const form=new FormData(e.currentTarget);const body:RecordData={};for(const field of definition.fields){if(field.readOnly)continue;const value=field.type==='boolean'?form.get(field.key)==='on':form.get(field.key);if(value!==null)body[field.key]=value;}const url=editing?`/api/admin/${resource}/${editing.id}`:`/api/admin/${resource}`;const r=await fetch(url,{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setError(d.error||'تعذر الحفظ');return;}setOpen(false);setEditing(null);await load();}
 async function remove(item:RecordData,hard=false){const warning=hard?'حذف نهائي لا يمكن استرجاعه. هل أنت متأكد؟':'سيتم نقل السجل إلى المحذوفات. هل أنت متأكد؟';if(!confirm(warning))return;const r=await fetch(`/api/admin/${resource}/${item.id}${hard?'?hard=1':''}`,{method:'DELETE'});const d=await r.json();if(!r.ok){alert(d.error||'تعذر الحذف');return;}await load();}
 async function restore(item:RecordData){const r=await fetch(`/api/admin/${resource}/${item.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({__action:'restore'})});if(!r.ok){alert('تعذر الاسترجاع');return;}await load();}
 function showForm(item:RecordData|null){setEditing(item);setOpen(true);setError('');}
 return <div><header className="pageHeader"><div><span className="eyebrow">Central data management</span><h1>{definition.title}</h1><p className="muted">إضافة وتعديل وأرشفة واسترجاع السجلات مع تسجيل كل عملية.</p></div><button className="btn primary" onClick={()=>showForm(null)}>+ إضافة {definition.singular}</button></header><section className="panel"><div className="panelHead"><div className="toolbar" style={{flex:1}}><input className="input search" placeholder="بحث..." value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&(setPage(1),void load())}/><button className="btn" onClick={()=>{setPage(1);void load()}}>بحث</button><label className="badge"><input type="checkbox" checked={deleted} onChange={e=>{setDeleted(e.target.checked);setPage(1)}}/> عرض المحذوفات</label></div><span className="badge">{total.toLocaleString('ar-EG')} سجل</span></div>{error&&<div style={{padding:15}}><div className="errorBox">{error}</div></div>}{loading?<div className="empty">جاري التحميل...</div>:items.length===0?<div className="empty">لا توجد بيانات مطابقة.</div>:<div className="tableWrap"><table><thead><tr>{definition.columns.map(c=><th key={c}>{definition.fields.find(f=>f.key===c)?.label||c}</th>)}<th>الإجراءات</th></tr></thead><tbody>{items.map(item=><tr key={item.id}>{definition.columns.map(c=><td key={c}>{c==='status'?<span className="badge">{formatValue(item[c],c)}</span>:formatValue(item[c],c)}</td>)}<td><div className="actions">{item.deletedAt?<><button className="iconBtn" onClick={()=>restore(item)}>استرجاع</button><button className="iconBtn" onClick={()=>remove(item,true)}>حذف نهائي</button></>:<><button className="iconBtn" onClick={()=>showForm(item)}>تعديل</button><button className="iconBtn" onClick={()=>remove(item)}>حذف</button></>}</div></td></tr>)}</tbody></table></div>}<div className="pagination"><span>صفحة {page} من {pages}</span><div className="toolbar"><button className="btn" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>السابق</button><button className="btn" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>التالي</button></div></div></section>{open&&<div className="modalBackdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><form className="modal" onSubmit={save}><div className="modalHead"><strong>{editing?'تعديل':'إضافة'} {definition.singular}</strong><button type="button" className="iconBtn" onClick={()=>setOpen(false)}>✕</button></div>{error&&<div style={{padding:'15px 22px 0'}}><div className="errorBox">{error}</div></div>}<div className="formGrid">{definition.fields.filter(f=>!f.readOnly).map(field=><Field key={field.key} field={field} initial={editing?.[field.key]} options={options[field.key]||[]}/>)}</div><div className="modalFoot"><button className="btn primary">حفظ</button><button type="button" className="btn" onClick={()=>setOpen(false)}>إلغاء</button></div></form></div>}</div>
}
function Field({field,initial,options}:{field:FieldDefinition;initial:any;options:{value:string;label:string}[]}){const full=field.type==='textarea'||field.type==='json';const common={name:field.key,required:field.required,defaultValue:initial==null?'':field.type==='json'&&typeof initial==='object'?JSON.stringify(initial,null,2):field.type.includes('date')?String(initial).slice(0,field.type==='date'?10:16):initial} as any;return <div className={`field ${full?'full':''}`}><label>{field.label}{field.required?' *':''}</label>{field.type==='textarea'||field.type==='json'?<textarea className="textarea" {...common}/>:field.type==='select'?<select className="select" {...common}><option value="">— اختر —</option>{field.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:field.type==='relation'?<select className="select" {...common}><option value="">— غير محدد —</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:field.type==='boolean'?<input name={field.key} type="checkbox" defaultChecked={Boolean(initial)} style={{width:20,height:20}}/>:<input className="input" type={field.type==='email'?'email':field.type==='number'||field.type==='money'?'number':field.type==='date'?'date':field.type==='datetime'?'datetime-local':'text'} step={field.type==='money'?'0.01':undefined} {...common}/>}</div>}
