import { site } from '@/data/site';

type Stat = { label: string; value: string; trend: string };
type RecordItem = { id: string; title: string; meta: string; status: string; amount: string };

function Status({value}:{value:string}) {
  return <span className="rounded-full bg-white/80 px-3 py-1 text-xs font-semibold text-slate-700 ring-1 ring-slate-200">{value}</span>;
}

function KpiGrid({stats}:{stats: readonly Stat[]}) {
  return <div className="grid gap-4 md:grid-cols-4">{stats.map((s) => <div key={s.label} className="rounded-3xl bg-white p-5 card-shadow ring-1 ring-slate-100"><p className="text-xs uppercase tracking-[.2em] text-slate-400">{s.label}</p><h3 className="mt-3 text-3xl font-black text-slate-950">{s.value}</h3><p className="mt-2 text-sm font-semibold text-emerald-600">{s.trend}</p></div>)}</div>;
}

function DataTable({records}:{records: readonly RecordItem[]}) {
  return <div className="overflow-hidden rounded-3xl bg-white card-shadow ring-1 ring-slate-100"><div className="flex items-center justify-between border-b border-slate-100 p-5"><h3 className="font-black text-slate-950">Live records</h3><button className="rounded-full bg-slate-950 px-4 py-2 text-sm font-bold text-white">Export</button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-[.2em] text-slate-400"><tr><th className="p-4">ID</th><th className="p-4">Record</th><th className="p-4">Meta</th><th className="p-4">Status</th><th className="p-4 text-right">Amount</th></tr></thead><tbody>{records.map((r) => <tr key={r.id} className="border-t border-slate-100"><td className="p-4 font-bold text-slate-500">{r.id}</td><td className="p-4 font-black text-slate-900">{r.title}</td><td className="p-4 text-slate-500">{r.meta}</td><td className="p-4"><Status value={r.status}/></td><td className="p-4 text-right font-black">{r.amount}</td></tr>)}</tbody></table></div></div>;
}

function ModuleCards() {
  return <div className="grid gap-4 md:grid-cols-3">{site.modules.map((m, idx) => <a key={m.slug} href={`/${m.slug}`} className="group rounded-3xl bg-white p-5 ring-1 ring-slate-100 transition hover:-translate-y-1 hover:shadow-2xl"><div className="flex items-center justify-between"><span className="rounded-2xl px-3 py-1 text-xs font-black text-white" style={{background: site.accent}}>{String(idx+1).padStart(2,'0')}</span><span className="text-xs font-bold text-slate-400">Open</span></div><h3 className="mt-6 text-xl font-black text-slate-950">{m.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{m.description}</p></a>)}</div>;
}

export function HomePage() {
  const bg = { background: `radial-gradient(circle at top left, ${site.soft}, transparent 35%), linear-gradient(135deg, ${site.dark}, #020617)` };
  if (site.layout === 'split') return <main className="min-h-screen"><section style={bg} className="grid min-h-screen lg:grid-cols-2"><div className="p-8 text-white lg:p-16"><p className="font-bold uppercase tracking-[.3em] text-white/60">{site.category}</p><h1 className="mt-8 max-w-2xl text-5xl font-black leading-tight lg:text-7xl">{site.title}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/70">{site.description}</p><div className="mt-8 flex gap-3"><a href="/dashboard" className="rounded-full bg-white px-6 py-3 font-black text-slate-950">Open dashboard</a><a href="/api/health" className="rounded-full border border-white/20 px-6 py-3 font-black text-white">API health</a></div></div><div className="p-8 lg:p-16"><div className="rounded-[2rem] bg-white/95 p-6 card-shadow"><KpiGrid stats={site.stats}/><div className="mt-6"><ModuleCards/></div></div></div></section></main>;
  if (site.layout === 'kanban') return <main className="min-h-screen bg-slate-100 p-6"><header className="rounded-[2rem] p-8 text-white" style={bg}><h1 className="text-5xl font-black">{site.title}</h1><p className="mt-3 max-w-3xl text-white/70">{site.description}</p></header><section className="mt-6 grid gap-5 lg:grid-cols-4"><aside className="rounded-3xl bg-white p-5 card-shadow"><h2 className="text-xl font-black">Modules</h2>{site.modules.map(m => <a className="mt-3 block rounded-2xl bg-slate-50 p-3 font-bold text-slate-700" href={`/${m.slug}`} key={m.slug}>{m.title}</a>)}</aside><div className="lg:col-span-3 grid gap-4 md:grid-cols-3">{['Backlog','In Progress','Review'].map(stage => <div key={stage} className="rounded-3xl bg-white p-5 card-shadow"><h3 className="font-black">{stage}</h3>{site.records.slice(0,4).map(r => <div key={stage+r.id} className="mt-4 rounded-2xl bg-slate-50 p-4"><p className="font-black">{r.title}</p><p className="text-sm text-slate-500">{r.meta}</p><div className="mt-3"><Status value={r.status}/></div></div>)}</div>)}</div></section></main>;
  if (site.layout === 'dense') return <main className="min-h-screen bg-slate-950 p-4 text-slate-100"><div className="grid gap-4 lg:grid-cols-[280px_1fr]"><aside className="rounded-3xl border border-white/10 bg-white/5 p-5"><h1 className="text-2xl font-black">{site.title}</h1><p className="mt-2 text-sm text-slate-400">{site.description}</p>{site.modules.map(m => <a href={`/${m.slug}`} key={m.slug} className="mt-3 block rounded-2xl bg-white/5 p-3 font-bold text-slate-200">{m.title}</a>)}</aside><section className="space-y-5"><KpiGrid stats={site.stats}/><DataTable records={site.records}/></section></div></main>;
  if (site.layout === 'mobile') return <main style={bg} className="min-h-screen p-8"><div className="mx-auto max-w-7xl"><div className="grid items-center gap-10 lg:grid-cols-[1fr_460px]"><section className="text-white"><p className="font-bold uppercase tracking-[.3em] text-white/60">Mobile-first system</p><h1 className="mt-5 text-6xl font-black leading-tight">{site.title}</h1><p className="mt-5 text-lg leading-8 text-white/70">{site.description}</p><div className="mt-8"><ModuleCards/></div></section><section className="rounded-[3rem] bg-slate-950 p-4 shadow-2xl ring-8 ring-white/10"><div className="rounded-[2.5rem] bg-white p-5"><div className="mx-auto mb-4 h-1 w-24 rounded-full bg-slate-200"/><KpiGrid stats={site.stats.slice(0,4)}/><div className="mt-5 space-y-3">{site.records.slice(0,4).map(r => <div className="rounded-2xl bg-slate-50 p-4" key={r.id}><p className="font-black">{r.title}</p><p className="text-sm text-slate-500">{r.meta}</p></div>)}</div></div></section></div></div></main>;
  if (site.layout === 'desktop') return <main className="min-h-screen bg-slate-200 p-6"><div className="rounded-[2rem] bg-slate-900 p-3 shadow-2xl"><div className="flex gap-2 px-4 py-3"><span className="h-3 w-3 rounded-full bg-red-400"/><span className="h-3 w-3 rounded-full bg-yellow-400"/><span className="h-3 w-3 rounded-full bg-green-400"/></div><div className="grid min-h-[720px] gap-4 rounded-[1.5rem] bg-white p-5 lg:grid-cols-[260px_1fr]"><aside className="rounded-2xl bg-slate-950 p-4 text-white"><h1 className="text-2xl font-black">{site.title}</h1>{site.modules.map(m => <a href={`/${m.slug}`} key={m.slug} className="mt-3 block rounded-xl bg-white/10 p-3 font-bold">{m.title}</a>)}</aside><section className="space-y-5"><KpiGrid stats={site.stats}/><DataTable records={site.records}/></section></div></div></main>;
  if (site.layout === 'ai') return <main className="min-h-screen bg-slate-950 p-6 text-white"><div className="mx-auto max-w-7xl"><header className="rounded-[2rem] p-8" style={bg}><h1 className="text-5xl font-black">{site.title}</h1><p className="mt-4 max-w-3xl text-white/70">{site.description}</p></header><section className="mt-6 grid gap-5 lg:grid-cols-[1fr_380px]"><div className="rounded-3xl bg-white p-5 text-slate-950"><label className="text-sm font-black uppercase tracking-[.2em] text-slate-400">Prompt / command</label><div className="mt-3 rounded-2xl border border-slate-200 bg-slate-50 p-5 text-slate-500">Ask the system to analyze, generate, classify, or automate...</div><div className="mt-4 rounded-2xl p-5 text-white" style={{background: site.dark}}><h3 className="font-black">AI result area</h3><p className="mt-2 text-sm text-white/70">Structured response, confidence, next actions, and audit trail preview.</p></div><div className="mt-5"><DataTable records={site.records}/></div></div><aside className="space-y-4"><KpiGrid stats={site.stats}/><ModuleCards/></aside></section></div></main>;
  if (site.layout === 'chat') return <main className="min-h-screen bg-slate-100 p-6"><div className="grid gap-5 lg:grid-cols-[300px_1fr_360px]"><aside className="rounded-3xl bg-white p-5 card-shadow"><h1 className="text-2xl font-black">{site.title}</h1>{site.modules.map(m => <a href={`/${m.slug}`} className="mt-3 block rounded-2xl bg-slate-50 p-3 font-bold" key={m.slug}>{m.title}</a>)}</aside><section className="rounded-3xl bg-white p-5 card-shadow"><h2 className="text-3xl font-black">Conversation workspace</h2>{site.records.slice(0,6).map((r, i) => <div key={r.id} className={`mt-4 max-w-[80%] rounded-3xl p-4 ${i%2 ? 'ml-auto text-white' : 'bg-slate-100'}`} style={i%2 ? {background: site.dark} : {}}><p className="font-black">{r.title}</p><p className="text-sm opacity-70">{r.meta}</p></div>)}<div className="mt-6 rounded-2xl border border-slate-200 p-4 text-slate-400">Type a message or command...</div></section><aside className="space-y-4"><KpiGrid stats={site.stats}/></aside></div></main>;
  return <main className="min-h-screen bg-slate-50"><section style={bg} className="p-8 text-white lg:p-16"><p className="font-bold uppercase tracking-[.3em] text-white/60">{site.category}</p><h1 className="mt-5 max-w-5xl text-6xl font-black leading-tight">{site.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/70">{site.description}</p></section><section className="mx-auto max-w-7xl space-y-6 p-6"><KpiGrid stats={site.stats}/><ModuleCards/><DataTable records={site.records}/></section></main>;
}

export function ModulePage({moduleSlug}:{moduleSlug:string}) {
  const module = site.modules.find(m => m.slug === moduleSlug) || site.modules[0];
  return <main className="min-h-screen bg-slate-50"><header className="p-8 text-white" style={{background: `linear-gradient(135deg, ${site.dark}, ${site.accent})`}}><a href="/" className="font-bold text-white/70">← Back</a><h1 className="mt-6 text-5xl font-black">{module.title}</h1><p className="mt-3 max-w-3xl text-white/75">{module.description}</p></header><section className="mx-auto grid max-w-7xl gap-6 p-6 lg:grid-cols-[1fr_360px]"><div className="space-y-6"><KpiGrid stats={site.stats}/><DataTable records={site.records}/></div><aside className="rounded-3xl bg-white p-5 card-shadow"><h3 className="text-xl font-black">Module actions</h3>{['Create record','Import CSV','Generate report','Configure approval','Review audit log'].map(a => <button key={a} className="mt-3 w-full rounded-2xl bg-slate-50 p-4 text-left font-bold text-slate-700">{a}</button>)}</aside></section></main>;
}
